configured_endpoints: 27
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/replicate-mpatankar%2Freplicate-client-e6d33ab6eefa3c8d7a322723d5eb38b10125260c59f41cb6adeb066996737a20.yml
