configured_endpoints: 27
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/replicate-mpatankar%2Freplicate-client-1dc2101f173bcb6df38cf0973306968b9c970dbd2cb86a0bc63839ee720edba3.yml
